# Experimental workflow to test GitHub Actions.

name: Experimental Workflow

on:
  workflow_dispatch:

jobs:

  checkout-code:

    name: Checkout Code
    runs-on: ubuntu-18.04

    # environment:
    #   name: production
    #   url: https://purpleturtlecreative.com/

    steps:

      # Download All Code.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.PTC_GITHUB_PAT }}

      # Build Completionist.
      - name: Build Completionist
        uses: ./wp-content/plugins/completionist

      # Remove unnecessary files and directories.
      - name: Clean Up
        run: |
          find . -name '.git*' -print -exec rm -rfv {} \;
          find . -type d -empty -print -delete

      # Upload Code to Production.
      - name: Sync Code to Production
        env:
          destination: "github@${{ secrets.PTC_PROD_HOSTNAME }}:/home/github/release"
        run: |
          echo "${{ secrets.PTC_GITHUB_SSH_KEY }}" > deploy_key
