# Experimental workflow to test GitHub Actions.

name: Experimental Workflow

on:
  workflow_dispatch:

jobs:

  checkout-code:

    name: Checkout Code
    runs-on: ubuntu-18.04

    environment:
      name: production
      url: https://purpleturtlecreative.com/

    steps:

      # Download All Code.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.PTC_GITHUB_PAT }}

      # Confirm Downloaded Code.
      - name: Print Working Dir
        run: pwd
      - name: List Working Dir Contents
        run: ls -la
      - name: List Plugins
        run: ls wp-content/plugins
      - name: List Themes
        run: ls wp-content/themes
      - name: List Submodule, Completionist
        run: ls wp-content/plugins/completionist
      - name: List Submodule, PTC Theme
        run: ls wp-content/themes/purple-turtle-creative

      # @TODO - Build completionist code using its own workflow file.

      # Upload Code to Production.
      - name: Sync Code to Production
        env:
          destination: "github@${{ secrets.PTC_PROD_HOSTNAME }}:/home/github/release"
        run: |
          echo "${{ secrets.PTC_GITHUB_SSH_KEY }}" > deploy_key
